language: node_js
cache: npm
node_js:
- node
branches:
  only:
  - master
install:
- npm install
script:
- CI=false npm run build
deploy:
  provider: firebase
  edge: true
  project: beerxp-dev
  token:
    secure: ACYquiGraxYkNzPmmXaB1TkiU1Fi97HWzeHQEI6oIXpjS5I8JrcBUbAYGr2LfV/132gk9Np/z0Eixene5rOEPa+5lx05m4BtaXqktUh18zqUf3vt3lFWyfinoFNl/YWDkPrp3D+rPColvUl6FSx/fhK7IOS1WOAyMXzUh/MKm+cEtqzcBM1jYxwp5EArllIiQAVeef8y9lzx01XFp+ovtmZCFQb9eS+j6oLEIjumHXdOoXNapNToTKM4rHodtDLPvJrh9KtFHtUEnZJAwxgOA0N6yVFV8fwvesqA4YZkz5hfPR+HEXHgB+wgdKGoAtCC9eYcPvy/KlDacsT4tT2w8usm2ZyLfmdAZIDBOBq1rzDegbrG/babjtgrS4LiQxtjvIuUpsOOsaZI+jvttQqkbY2sV7t4P0e3JqfjYz+sWrBNNTfP2GZ2WHXEFSWfDIr1hcywtzzkJMyJEL67UTfFTvz4Q/7PISaL3WIPmTlCSBED7VjfNovCJiXQlQw03h/S5reYWmuw+VqoOhzDIqclw4gCaRkIDUleUirMfQrN5fxkdHA6jhjhiHaC/lzXROPDyyQBlFuL6VEBvD3qNwjErKfYegH9Bz0CQIyTQEKJbbMh445/nVrBt3tvjfr9HfPA+jX77CMvpWV06IEPEPz9xJM0KnMCVrLws1CEyHGNkj4=
notifications:
  slack:
    secure: U+4HCQ/i4MilF1Ge5RD9l/7tT4iKdUPYjOCMd8uL0a+/2a2tdxMrgWa+sXHbXGqdhlouRZABPq0rjuARmkPuu1abinCx2W79pambctZSogqUHGqApLUmOgv3yfRfs4wN43G/2BtfwOFyQ9XBe1HtBRZUjMFm20E33OojrJ5tz67BEayIa4R/ZFR7zD5KDWeitfXgavCPT7o9g91b3en2tdprF2CfotkJNNhGwtyy51KTVMRvzx1b6eQxNVTgyP4NcFgiXnYK/rqM1e6bE7FTotw3DryjvzXT9UEcfB5AzaMBdwj9tyrKQAd2qw+fmSEdv86g2UzgOgxnL+l5tFjZLmo5sJbFFQWxJ6+RcpcxtrjdJMx18pILpH0JxT49tiO/bl1bpGUNUQ8niKWvooDKw6f4jJVH0TMYozIXnCh7PPlYbtSDx8qWRRJ2fgkpR2CpnBkS4MDztzyflN2+3D94p3NvFDH24lA/ym0cQ9/gyiwG9otB9AtbvVYOoCVZ97bc+GMG+0qCrgH3VRpc8kSrHvkD0O4Wi7i1ACz5BCY4pN3QxqOseIAvpWAh/j+m7g8rNpKJwQlSMrmR9Tr0e9wPCX+3N2fR6SHLsK2NuiyjXxE8H90AAApGd8Q0xxgQMXIS+QxXq1JB5RqYAWVSX2C1PH0WwyHEIbbizT97C1nRkls=
