language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    token:
        secure: MVOtUYKlJBapReDkq6ufR+yf5IEtrQip1V4CnjrJvS49m7yMor5xzSfAOw9qHFhkp1ItljKsndR4KPFSbWRY90rUn03KLkcZ7Of7xq2dqzFbfhA0A6iGUPIMuFxOM/8CtfF5IP+g6KktWPvJGq106J3fqEXPjkGuW2H8dzYJed9DuvURD0XJwd+ISoHX/uViN4mGkuoCpAz5HNm7XnlEPeXQbhn0Bt8NUCD+pT0c1iRjeC5HS+IG46a2QG8hTmFAe4HWBXMoBv91qLehsLw8lCY5HDwUZ08dt//zfR1eu5OGc22wgS8FmWM9u20vAvT8YY/eiidLMKLg0+IThW14IP5dVXOR6O/sf13trE8nP12hx0Qs9a0CXOpT2hOGc92ws0Vm5mdCxqfA6JqWWy+ixUU87LNVGDX/dv1C9JBYFZwMnSvTmplZGjwezehm4/9aqB/vmHCE0LJ7QF+W/PCOhWEkYTX0PmYzjyjPUYP3/L2Gh5c65xdlRGaalghDOEocKUkNpMyFMFhrgXcAyKgVse1dWO4WxYFJuQOA3de/mC9qgaP5zCeW//0wv/qJSAstytQJYtO9RiU5rd5OO3RBQpYctRC8k92VJ4X+4x+bxix3h/DDt1unIcGvgcWOt+TehEuJWkCyy/L+ToiIJxqyyb+QW1ufqq9CqmIaYj0undk=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
