language: node_js
cache: npm
node_js:
- node
git:
  autocrlf: input
branches:
  only:
  - master
install:
- npm install
script:
- CI=false npm run build
deploy:
  provider: firebase
  edge: true
  project: beerxp-dev
  token:
    secure: ACYquiGraxYkNzPmmXaB1TkiU1Fi97HWzeHQEI6oIXpjS5I8JrcBUbAYGr2LfV/132gk9Np/z0Eixene5rOEPa+5lx05m4BtaXqktUh18zqUf3vt3lFWyfinoFNl/YWDkPrp3D+rPColvUl6FSx/fhK7IOS1WOAyMXzUh/MKm+cEtqzcBM1jYxwp5EArllIiQAVeef8y9lzx01XFp+ovtmZCFQb9eS+j6oLEIjumHXdOoXNapNToTKM4rHodtDLPvJrh9KtFHtUEnZJAwxgOA0N6yVFV8fwvesqA4YZkz5hfPR+HEXHgB+wgdKGoAtCC9eYcPvy/KlDacsT4tT2w8usm2ZyLfmdAZIDBOBq1rzDegbrG/babjtgrS4LiQxtjvIuUpsOOsaZI+jvttQqkbY2sV7t4P0e3JqfjYz+sWrBNNTfP2GZ2WHXEFSWfDIr1hcywtzzkJMyJEL67UTfFTvz4Q/7PISaL3WIPmTlCSBED7VjfNovCJiXQlQw03h/S5reYWmuw+VqoOhzDIqclw4gCaRkIDUleUirMfQrN5fxkdHA6jhjhiHaC/lzXROPDyyQBlFuL6VEBvD3qNwjErKfYegH9Bz0CQIyTQEKJbbMh445/nVrBt3tvjfr9HfPA+jX77CMvpWV06IEPEPz9xJM0KnMCVrLws1CEyHGNkj4=
notifications:
  slack:
    secure: Ky16QpmDemJ4gwIxFJfvqpZ/J83U28oyb4Ux1Nwuw+xD3567eReRSH1AA28hR3pVMbLVaXV1KqUC41AbVb5cWEqBd6J2ov4w7PSmkpDwfVI+v3f0P7QMGbyODC1YUqFawkBjefbozlOn5amH7rM0Lb9CNX/xxBTZ4laUv9w+JOLQTEXrXVuUvra68bRLwlW4e9RTpWzG5JUfdJjFXtz5AtQ0t6DckYRn179msCYaIuFqRi9RlO+Fgp6c7KrgW8uNdvAq5Uaul/6sSLI9G+ZcDhXoXJ5jGOwL6XabMC3VpJCo4wZjt6R55oBclrvVez0kDbW8JuXRbS6/I64QDASdVvErDM+GMir4GQS+RP2T1gENDvwk1Me0FUmYnnL4tWT1hp4p+kE2101/thzauHNbhQp1CiNS9Pfdhx9qjyD66GGkNHk0taheiFl/ymnYw8EIaWebh8bo2WvRG91coAcueicBj9r+WvLqxC/Kz+0CsyYDTMoRjnbPlZrSUqaOjmJFFjSuEEVnLgJekf9rWK1/nA6eMl58Qu7XQOZlyotPR+Vrn6Tm30VnFK5U3urPl2wqsCL1d2AvsjvPEKt8MfRJI7msLosf+BvszyVjoZMHQcT8N3JLpMiZ8uKm5N4+ur5KUnWKPu11To5bLCXUnLyripZo2SlkpAZZT5vZbwM6C8Q=
SNYK_TOKEN:
  secure: D/psJJU5LjNgQ5hOqv/7wuKujOVJMk7WU+WGw20Jbys22EtLZp+g3VgcxMC4jPcaKLE5qm2CZcriBGKRI5wZ4GomnggZFA7vK7rg49aUBXQOdKF+ve7Jud6Z/sP57imN+aw2B4jQNHLZJCZQfPw4/HVemPuiEUu72sJxrBlw6irOvA9RnUBMK8Mfm884kNAm2t3XMssUCkLh3pB+YjRUgpnP9bta8VSF6p5Vn3d96az+J5+Dr5QNjVhgMDita3DABBLqR92twCCOAJkqHXnVxTY2+fh56qY+Gur5lS7Bnj7AqK9v7dn2FPEa51DlhWVd6MgIh/H9T0lFlSCtvHjYju5ouW7Wzxzov16IX0RgeRRTNE7tlg/5qs9fDpugHaqqytueuMRSr1zX1EFATeN4VSPi+5ym2kBSwDzzdsU5LjWcBNxIZozGBIW24MjjPyGhunrJf/yIIIbTI3xY7PfMc13nygvsPEr2u1Od8MUMWU28y3v9dWwjohBOG6XOX+WGrTh8XiQB6KlK+j2gHjCAuSxYseLTr3jBjyIms154O4RZypZ6BUTqf0zdTIsn9TOGh2R+DHhO/OCX7Ybj5wHntBqKEBoBiACLw3gfAIbzNtRvH70QAPCqmvXyxvXpmh0RRLT14Z019/AHGYRJZf52KupXp6+N6vZb0zZ1PGAVyCk=
