language: node_js
node_js:
    - node
branches:
    only:
        - master
before_script:
    - npm install -g firebase-tools
    - npm install -g preact-cli
    - npm install
deploy:
    provider: firebase
    token:
        secure: xrUjYkLgRXs16GkGxQzWvObBaAZuIAn3DsfEVNqfXoqcBBfkFMtC9nPKOoVSWK28XUQ9C3cGComu3Qfn8hSN53xBd6EQBuSvvGEXcKpBS5AzCfN1cFXlD7QWgMfAyaXR9GZHII/A39IRomHawkttNhkhRv9nt+YlMnbeG3xDB9wOB1vwn5aZIog0fb+7J6l5UbSLCKiENenJAo1j9KyBb5NDd7GZVx8KegLQuQb+U4Fu3I8xDSN44vKiF3L9T4hHrkm4GmoSzrybRuRfTPitSYUAdUxyXsvBNyNwPVJrWTLQ5At5Ou7m/VbS8D3XzeCx2v5ykgNYTIPL0KlS+PkwbsKSloPpNpW9FFtjlkC8jM7fI/0nbnYcu9LaN/QbnDVX8LA59NJw9IQWNTBYyYcwX8+R3Dz6uVkX0WjBnPpptjvXa+5Rbf/CWi9i+cfeMWOhwFUB3z/hXss/ULqhm5GrQzfFNfp60E+NtFvccEeK4Bm88H9xrG8vS9ZKNUpXAGCX9WUPpgEbJpD9dWrD7SiX23yzUpvD/o1uhTdU0FJe4zEj9d4Bg16yvTlQK9QdlFTzXp3JJ74fBstTEqb+o7PuCenJYpYgTeVnMqHCBJjlTy1jZqhHRBmhxM+EOpNOQZA5mtdxt7UC9OTrR/d15FVCDjkCSf+DnQd1A+Q9P3Z0LPQ=
