language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    token:
        secure: wsLYjifKjrI8azTvmFoSKoWrKLfPzaJvp8m7p5eeY2Rj/iH/tiUxEk+WaPL8rtr2RDyyNK3lzMSwKTBbqhw3h4w6oOLhiaTz5Lo+Zj66P2UvAx1TNkXQH0xX57hRR15uGiZ2+Z62AfOcwu9rN9z+cROpxihln/2yDiRo/AGQBebXgrYBeQzPDxoSSbLsvBp/6x8bvg7AeKBC0WKIQ8U+6FpXgoEl4DzcJ9TX5YDHWRDZXblI83RcY14+RvhZP8ygFnX0GV+csfgo6kBBdQMOo8jXgw8wC1c0YMlSQH9XyyxCXkM2CLVHyl60Z8KDHqxVXaeG5ydvTCbmBMRFRvDvXMziUDhpmewuhEUkihIx97i5bQHA6HY2mWhabHgHEQfPprPzk22bnrmpzLlskgmICLVs/MOua2EaisEfTAazxc3mVlVIbPKXO9cFSkzdNm8CmtOrpj55rNHXgK2sO87FCO/9t/syLKH+jdep18ujn+2QL6R5BxVI1a7CVgH8BmLyLgKQ2FpD1hR7exCTFpKBDw3mmqITq2qwPd0LMHU7knInuc/x2nQPF/bj7qn/3fIxE59eVfpPWz4amz9HXcSSoxXcRGnIjHoRME3U4otU9XXKM2OJrERzm5eNhRFOVdHb8I39szGrRw5q6N7ogK7QU+TZNqN3LjaJTaazrltYdoY=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
