language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    token:
        secure: sx3siuMkLhulIOmGhmTISFylfFf07XT9Rc6b8fQhH6ezA4hYSTk4m1+CVJoPecKvzh0lmLCOdsNEMLRHurlYbcMiz7CsFOY8+gVOM5q6DB+KJNtjZmixXJKWl4461YHG9+laMyDg+rlflvtu6S/TxDsTLL/bKapa5Z7J3TNXVkhcJPwETQF5i9FJKYyPyvTu2WJvyHpzK2Y6tbHVUUwzYvI+1H5UFc3/3RX94NHljTqTIaKSCmPmiDvDtivXGPORgaVhKVpcr1pX5QX8NouBPnWblWDKqH3EGTrtrwRG81KWUpqea9rl3BVxdLxwoAckH/vmR+SyEN08buo63bKa/dZ/2iyCJKAXvwrcFdDN7Wh7Juc2tk80u7OvzkUYSRkSISHccPpyWQW1bgHcC/qdxCILCdqFvf3IDTn5++rm6q52q/SJJ+dl9RXNa9lCPJMQqy429OvCFLjvc04U/pG2ULDvhrQ5ot7sAsBbTiPKCzRShXQ04yd6ALvQ8GNberY6IG5bqorCBhslXlcpj1oJh8TQMDQEE0z4wNEFrynjqkdjN2GBoz582H+83zLgR0oeA7nRq2tilPmZrj+FdcuwKhwFfKh6/qiiiRJvYTGa4IxazATzvY3fmRXRyuA0VXbZM3dYNLtBOewaEuvSW5db/zQLvk6CHhLvr0R8O2lC5mY=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
