language: node_js
cache: npm
node_js:
    - node
git:
    autocrlf: true
branches:
    only:
        - master
install:
    - npm install
script:
    - CI=false npm run build
deploy:
    provider: firebase
    edge: true
    project: beerxp-dev
    token:
        secure: ACYquiGraxYkNzPmmXaB1TkiU1Fi97HWzeHQEI6oIXpjS5I8JrcBUbAYGr2LfV/132gk9Np/z0Eixene5rOEPa+5lx05m4BtaXqktUh18zqUf3vt3lFWyfinoFNl/YWDkPrp3D+rPColvUl6FSx/fhK7IOS1WOAyMXzUh/MKm+cEtqzcBM1jYxwp5EArllIiQAVeef8y9lzx01XFp+ovtmZCFQb9eS+j6oLEIjumHXdOoXNapNToTKM4rHodtDLPvJrh9KtFHtUEnZJAwxgOA0N6yVFV8fwvesqA4YZkz5hfPR+HEXHgB+wgdKGoAtCC9eYcPvy/KlDacsT4tT2w8usm2ZyLfmdAZIDBOBq1rzDegbrG/babjtgrS4LiQxtjvIuUpsOOsaZI+jvttQqkbY2sV7t4P0e3JqfjYz+sWrBNNTfP2GZ2WHXEFSWfDIr1hcywtzzkJMyJEL67UTfFTvz4Q/7PISaL3WIPmTlCSBED7VjfNovCJiXQlQw03h/S5reYWmuw+VqoOhzDIqclw4gCaRkIDUleUirMfQrN5fxkdHA6jhjhiHaC/lzXROPDyyQBlFuL6VEBvD3qNwjErKfYegH9Bz0CQIyTQEKJbbMh445/nVrBt3tvjfr9HfPA+jX77CMvpWV06IEPEPz9xJM0KnMCVrLws1CEyHGNkj4=
notifications:
    slack:
        secure: Ky16QpmDemJ4gwIxFJfvqpZ/J83U28oyb4Ux1Nwuw+xD3567eReRSH1AA28hR3pVMbLVaXV1KqUC41AbVb5cWEqBd6J2ov4w7PSmkpDwfVI+v3f0P7QMGbyODC1YUqFawkBjefbozlOn5amH7rM0Lb9CNX/xxBTZ4laUv9w+JOLQTEXrXVuUvra68bRLwlW4e9RTpWzG5JUfdJjFXtz5AtQ0t6DckYRn179msCYaIuFqRi9RlO+Fgp6c7KrgW8uNdvAq5Uaul/6sSLI9G+ZcDhXoXJ5jGOwL6XabMC3VpJCo4wZjt6R55oBclrvVez0kDbW8JuXRbS6/I64QDASdVvErDM+GMir4GQS+RP2T1gENDvwk1Me0FUmYnnL4tWT1hp4p+kE2101/thzauHNbhQp1CiNS9Pfdhx9qjyD66GGkNHk0taheiFl/ymnYw8EIaWebh8bo2WvRG91coAcueicBj9r+WvLqxC/Kz+0CsyYDTMoRjnbPlZrSUqaOjmJFFjSuEEVnLgJekf9rWK1/nA6eMl58Qu7XQOZlyotPR+Vrn6Tm30VnFK5U3urPl2wqsCL1d2AvsjvPEKt8MfRJI7msLosf+BvszyVjoZMHQcT8N3JLpMiZ8uKm5N4+ur5KUnWKPu11To5bLCXUnLyripZo2SlkpAZZT5vZbwM6C8Q=
