language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    cleanup: true
    token:
        secure: nnDyLnGCwP8qexe/xLTJ85gIYcWSIaTfHYgal7q9dt5YGjd2spdKoJWaFNtsajXwDimVYpr+g6PvDr21aoYJ5mMGb9nhp/6Gt79LpAJcYkTzo2fQjSW8kiDallhcs742C6B1nNb1SKC0ebEXEFKeRaNdP+q5UA9eP0JzvyyrxSr2o0J6T35fd1KqsKmDfShV+L+Dly8IBaxBiXAy896nxjr8Rfgm8jdj6/0OeEe5gI4C+p7iw8AQ3Ohcjpowxtj5W/oBT0zLtvwuvzUdenERm6vkUkk0AmPB+4jwYZGKWNuOPcoScbHUlLNFLZl+FgoSEtNUhKESNpfneg+KBhMOpZO8mrwGMvJYUS+Rbplpo8SaVgKOK0VabU1aFCvk8VgRdNM9pcniOAAF5BHPvmpWF00jUvaAPQzip7f8FI/C0rN74phbL547ksGFVjhYfW90RTyE9DsV3YuY1I4GSnCRn4JAkitF5FOI+CAbtF4jJ1SJh1+f0xZ9GeaoMw6AwAxyyoo4qW31flxCtfK/uW1w0ij+ybZj0dYTZVtPMbTz96zoed0R5tuP0ODo3FnuUkqhF3ReNoV1eXp4ho05BNolKX1Iy8rgEtO9x4D7gAdqUGKKHcmbl4mzRfACe77pHAFQN+KRo2/fNuPW0hwa2XZn14/LEbaoXC1mXMTDpnPhsUQ=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
