language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    token:
        secure: Tk44J8ge3kMYqpc2aM5PqTDEZQ41AkhUOup81WrBneRdrlqh4gVAdq0qbC6wJkmMFoq/AZ07XDciTS8cTB8KbrDoFN6GFlSO4dxVM52/l5X0MtGPc7fZK9OR1qjXPGouZPv+Pg3Q6ywK64RXzu5wI4zP1beAcrTubdyD53mCwqF0YJ7G9AWD1uaphRgg14or2f2fh4ThaKtvw275stMhiU27LBC+fXnwtkDyz69W+hLt0BbPPhJhzucexL4j4dA9ZNrpJ98XxM2nF44fZy/7NnnVFRjkdMhHI30cBBiNgfCc7vCc4rqyX2olvb3WKTyUbjgCxAe3UBYJfdrVgJdujdd/5ThjPJBZR1oUOMiIjiSxKP0rETJgqX8pK0IX6R/KOwvE+98LUej3EemaSyTiomNr7bHuNBk8uh/81s7CjpNc6aFvDnYeW4WHW0xUSR/QDv7/UxSAfZfdOnp/cxVr4B0aDHIE/qVh5/4d1YuWYPXmsOZpCYVlQ+HxdCHN4TXOwv+UPBrczuqZQu9q1OjV3h5rKolMTKLaRA0BvQITzUK6BSUk52GjB7dvkRqU4mohpw3nn1Pw+JgWDKWEzlnxVrc/PN5CvGYpHx+AxGxFb8ENwSH0EJWwqSm/NFURZlXsCpC9+JmisU9gNmT/su5fk6yDv4iFfuXp0qSGSPgiDzQ=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
