language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    cleanup: true
    edge: true
    project: beerxp-dev
    token:
        secure: ACYquiGraxYkNzPmmXaB1TkiU1Fi97HWzeHQEI6oIXpjS5I8JrcBUbAYGr2LfV/132gk9Np/z0Eixene5rOEPa+5lx05m4BtaXqktUh18zqUf3vt3lFWyfinoFNl/YWDkPrp3D+rPColvUl6FSx/fhK7IOS1WOAyMXzUh/MKm+cEtqzcBM1jYxwp5EArllIiQAVeef8y9lzx01XFp+ovtmZCFQb9eS+j6oLEIjumHXdOoXNapNToTKM4rHodtDLPvJrh9KtFHtUEnZJAwxgOA0N6yVFV8fwvesqA4YZkz5hfPR+HEXHgB+wgdKGoAtCC9eYcPvy/KlDacsT4tT2w8usm2ZyLfmdAZIDBOBq1rzDegbrG/babjtgrS4LiQxtjvIuUpsOOsaZI+jvttQqkbY2sV7t4P0e3JqfjYz+sWrBNNTfP2GZ2WHXEFSWfDIr1hcywtzzkJMyJEL67UTfFTvz4Q/7PISaL3WIPmTlCSBED7VjfNovCJiXQlQw03h/S5reYWmuw+VqoOhzDIqclw4gCaRkIDUleUirMfQrN5fxkdHA6jhjhiHaC/lzXROPDyyQBlFuL6VEBvD3qNwjErKfYegH9Bz0CQIyTQEKJbbMh445/nVrBt3tvjfr9HfPA+jX77CMvpWV06IEPEPz9xJM0KnMCVrLws1CEyHGNkj4=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
