language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - echo "Skipping tests"
deploy:
    provider: firebase
    project: beerxp-dev
    token:
        secure: o38N1oD/7ME6JcrRDKvxu3PPZRsqoxG14WtoZmCqjelkS5uDah8+mhC1vWmgpmvNZOd1+7CvF0GntEA4S9n9iQj52irs2z86Zi+I5theIgrBIL9egjalcDD2AjqpGVOBN6L2rwKuXvAQswVe2Q4U7ExfQHvhPC9c9mUa3dseZJ5aTYeB5tFQ7UDOBT8FPrZXHHigJsVv9q9JICmlv2z6MEx3+ZL/fkaV6LkRFExCRWql6eaVS4JKnb+1QbbigHeQKyf4iCJ8BQ04v2jY0y8rhqzeus+KovNFNiUYQkKDMVCNjc00K6XWufgQAeI4k+Xcey2D4HwepoqdzOKg5CmJ8qMMGO5TG4LpN1jn9XFZEACZ6saIF3YoJx8TLxxFVD/MYI8X85hJnjfAPpgxMc4NNNRxq9C8nBy4jHqbL4DTB2o7+ElqQNeSmQkvehHiUcsjAfOS4H4ER9eJi80GO6iV+Ky19XLza5U8UOgdMCvFP2DTE/NRZJFGkFNrX/hNlbFe+1HBEwYkBOVgiK3M1l+EmFQ/Vy0xfZh/9bGVp/Y2v7wrxEqrvDfUsMWyFppDZ4JImOwQD4krQQ6Em94zaBKLxdM7uJBDK2km0ywtNf6Vhw+gdTZ1IRUzN+R/hbc7j+KWl2Ll/nzsuxLSyT5XZy2oI2RQbv4UegSBzz1ct0qUGDg=
notifications:
    slack:
        secure: KS2h2OOb/WPPn0l9DTYGAZNiYMH8VhmwOhvV99kKAoVLB7es4pxiv/FOc+j1c7u8BlYW9FmMXgW21sakEBAINvlOU7LNqER6iVlbSCMpsnkmlIeffyB26yfifNAcCDBVAGPb0NZGlws4pz7q79NCM9GbCTv1VIjfrnnyigq2rmoeN7mT+pih9sMdIFvjwXKGmPfUbtfYml4tw6nQpimN0RLmJ8NFZhkehoxccFCfunkt9phuwXOWb8ST8CsWQvqXFuP49/FTQJCzUQ6blViFYiUlvuj4WgqBfTaDIcCFndPQk3Jv4CrgLAIeu07lTCHY5Wnq5Y5CEHzNkMgy5GHdb5TYb0xXWa1G0dPWwo4dsLhk6WnXA6KFfR2SiK60I+Tu9TgYVYvn+NX/U2z57MhdXIRK5DGt2/L2RuUbJcWYuaag41WB2O6oQARQXWe3TTdDQi9+Orz2/YoH2plCr2KgaOwkDLJAn6YgBMRaL+mLdtc4IPvPMIONH1RwW4V/H/D6QsM9eXVLZwdC89jD1nEclAoc8kW0xSCwofSC2DyCOjtxN/zA043kca4/JVIIbFcVMY9FQWIg9FkfEtcHjULRygSkwi9i4A8ve5nlIUtp5Kze4IK/3/gQSTDkno6icqMq9Giafd//pgz6i/I7iRMT6kqaWbxuLbbnkDI30HHID00=
