language: node_js
cache: npm
node_js:
    - node
branches:
    only:
        - master
install:
    - npm install
script:
    - CI=false npm run build
deploy:
    provider: firebase
    edge: true
    project: beerxp-dev
    token:
        secure: ACYquiGraxYkNzPmmXaB1TkiU1Fi97HWzeHQEI6oIXpjS5I8JrcBUbAYGr2LfV/132gk9Np/z0Eixene5rOEPa+5lx05m4BtaXqktUh18zqUf3vt3lFWyfinoFNl/YWDkPrp3D+rPColvUl6FSx/fhK7IOS1WOAyMXzUh/MKm+cEtqzcBM1jYxwp5EArllIiQAVeef8y9lzx01XFp+ovtmZCFQb9eS+j6oLEIjumHXdOoXNapNToTKM4rHodtDLPvJrh9KtFHtUEnZJAwxgOA0N6yVFV8fwvesqA4YZkz5hfPR+HEXHgB+wgdKGoAtCC9eYcPvy/KlDacsT4tT2w8usm2ZyLfmdAZIDBOBq1rzDegbrG/babjtgrS4LiQxtjvIuUpsOOsaZI+jvttQqkbY2sV7t4P0e3JqfjYz+sWrBNNTfP2GZ2WHXEFSWfDIr1hcywtzzkJMyJEL67UTfFTvz4Q/7PISaL3WIPmTlCSBED7VjfNovCJiXQlQw03h/S5reYWmuw+VqoOhzDIqclw4gCaRkIDUleUirMfQrN5fxkdHA6jhjhiHaC/lzXROPDyyQBlFuL6VEBvD3qNwjErKfYegH9Bz0CQIyTQEKJbbMh445/nVrBt3tvjfr9HfPA+jX77CMvpWV06IEPEPz9xJM0KnMCVrLws1CEyHGNkj4=
notifications:
    slack:
        secure: m6h/O57X+NZd5E2CJBNfFReWfS+7UnQBiGR5Jv2UhgHm6sBFcAiNL0GTU+pNw6swtSH5GDQQt+ajBQksyYNnLRWJSg80avQ+pFcS8lv7IYArs05j9sTVfjp330XxuA1bO+lP137M/oHYKQdZve1rC0j2c2YnwpZhRIyAxIHPPZB3vlS21seJ7+7nG7pwTMw7tuabECaTIUJoeM2tnUpvE7OYoQ97531eBjbRzjjXKy8YokAcIjlWF5Zt11JNnfHN1SuGZZpPkdMHAaucZTlKRNn1vWwu4m06uqGvXWcdhIUPgvrYhri6QB+AnbBCDqNPp1xl1nSkdmqM02kl6XFROd37VmumMDs/1drLPB1esW2q9Vt0z+UVOa+7FTDyeX0LT9Wv+5cqL0K4QgoJkyaVkfh6nKt5CjYdNBGoCK4ZUnXH4pwvFHFRvOgjeAJShIMlpRhGtd/JR16gDtM76DPfrGH76vZJhKIGOydYrX/RHPaPPF+AjZGKmXEy5IAL3W79dzFURlgkyx8Lfg4GZPYhGKkf9oNN/09dLl+62OLRPgtkKOCH/WRwbDC76q5x0yvEPveamQsiDJW1MQ+6izoAeOoiV9QO4yX7w0IRgdOvE09yfw6IQV0eIdznK4MV7wmGgefsrDtiQuRFSLrciDQQ0ZFFwRPiKz4pC+UiSPduf8c=
